### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mattwthompson**
Hey Zijie & Phillp - 

This repo is a nice start; I've gone through and cleaned up a handful of things, trimming some stuff down and moving things around. Right now I think the most pressing need is a suite of unit tests. This would not only provide some testing for the software but help define the scope of what this plugin does and does not try to accomplish

Let me know if you have any questions about these changes I propose; they are by no means canon

### CODE REVIEW

**Comment by zijiewu3** [comment]
Thanks Matt, I had a quick glance and I think most of them make a lot of sense. I will have a closer look once I am back in Delaware. I might also need further help from you to write reasonable unit tests.

**Comment by mattwthompson** [comment]
Please let me know if you need any help with this. Feel free to ask questions here or reach out on other platforms

**Comment by zijiewu3** [comment]
Will do, thanks!

**Comment by zijiewu3** [comment]
Hey Matt~
I tested everything out and am going to merge basically all your changes. Thanks a lot! I have a question though; What would you suggest is an appropriate way for us to integrate the topology file writer (or do we want to include a topology file writer at all?) Since you removed the member function in the DNA class that outputs the lammps data file based on the XML file.

**Comment by mattwthompson** [comment]
The LAMMPS data file format fully specifies the chemical topology in most workflows. The input script should be handled by a separate script generator or package, as it is not in the scope of mBuild or MoSDeF (currently).

**Comment by zijiewu3** [comment]
Agreed, but the lammps data file (not the input file) writer is also removed from the DNA class in your PR. Should we still include the data file writer in the DNA class?

**Comment by mattwthompson** [comment]
You should use the LAMMPS data file writer in mBuild for now, and soon the
writer in the new backend. Any behavior not currently supported by this
writer needs to be reported and added so that all users can take advantage
of it

https://github.com/mosdef-hub/mbuild/blob/master/mbuild/formats/lammpsdata.py

**Pull request merged**
